
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/cow_session
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: test1234

  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        show_sql: true
        format_sql: true
